# Generated by Django 4.0.3 on 2022-03-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_remove_user_fact_read_remove_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('imgURL', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
