# Generated by Django 4.0.3 on 2022-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_imgurl_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imgURL',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='imgURL',
            field=models.URLField(null=True),
        ),
    ]
