# Generated by Django 4.0.3 on 2022-03-21 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('discount', models.CharField(max_length=30)),
                ('preCoin', models.IntegerField()),
                ('newCoin', models.IntegerField()),
                ('imgURL', models.URLField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('fact', 'user')},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fact', 'user')},
            },
        ),
    ]
