# Generated by Django 4.0.3 on 2022-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reward_alter_bookmark_unique_together_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_start_date',
            field=models.DateField(null=True),
        ),
    ]
