# Generated by Django 4.0.3 on 2022-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usertasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='ref',
            field=models.URLField(blank=True, null=True),
        ),
    ]
