# Generated by Django 4.0.3 on 2022-03-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_savedcategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedCategories',
            new_name='UserInterest',
        ),
    ]
