# Generated by Django 4.0.3 on 2022-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_categoryrequest_iscompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='isAd',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
